routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Route::get('cache', function () {
    Artisan::call('cache:clear');
    Artisan::call('config:clear');
    Artisan::call('view:clear');

    dd('success');
});

Route::redirect('/', 'login');

Auth::routes();

Route::get('test', 'testController@index');


Route::group(['prefix' => 'admin', 'as' => 'admin.', 'namespace' => 'Admin', 'middleware' => ['auth', 'admin']], function () {
    Route::resource('messages', 'AdminMessageController');
    Route::resource('department', 'AdminDepartmentController');
    Route::resource('user', 'AdminUserController');
    Route::resource('task', 'AdminTaskController');
    Route::resource('set', 'AdminSetController');
    Route::resource('role', 'AdminRoleController');
    Route::resource('achievement', 'AdminAchievementsController');
    Route::resource('profile', 'AdminProfileController');
    Route::post('image-upload', 'AdminProfileController@imageUploadPost')->name('image.upload.post');

    //Route::get('profile', 'AdminController@editProfile')->name('profile');
    // Route::get('profile', 'AdminController@editProfile')->name('profile');
    Route::put('profile', 'AdminController@updateProfile')->name('profile.update');
    Route::put('password', 'AdminController@updatePassword')->name('profile.password');

});


//////////////////////////// Last Update /////////////////////////////
Route::group(['prefix' => 'set', 'as' => 'set.', 'namespace' => 'Set', 'middleware' => ['auth', 'sets']], function () {

    Route::resource('department', 'SetDepartmentController');
    Route::resource('user', 'SetUserController');
    Route::resource('profile', 'SetProfileController');
    Route::post('image-upload', 'SetProfileController@imageUploadPost')->name('image.upload.post');

//////////////////////////// Last Update /////////////////////////////

//    Route::resource('task', 'SectionTaskController');
//    Route::resource('user', 'SectionUserController');
//    Route::resource('collection', 'SectionCollectionController');
//    Route::get('profile', 'DepartmentController@editProfile')->name('profile');
//    Route::put('profile', 'DepartmentController@updateProfile')->name('profile.update');
//    Route::put('password', 'DepartmentController@updatePassword')->name('profile.password');
});


Route::group(['prefix' => 'department', 'as' => 'department.', 'namespace' => 'Department', 'middleware' => ['auth', 'department']], function () {
//    Route::resource('collection', 'DepartmentCollectionController');
//    Route::resource('section', 'DepartmentSectionController');
    Route::get('home', function () {
        return view('Department.home');
    })->name('home');
    Route::resource('user', 'DepartmentUserController');
    Route::resource('task', 'DepartmentTaskController');
    Route::resource('ach', 'DepartmentAchController');
    Route::get('profile', 'ProfileController@index')->name('profile');
//    Route::put('profile', 'DepartmentController@updateProfile')->name('profile.update');
//    Route::put('password', 'DepartmentController@updatePassword')->name('profile.password');
    //Datatables
    Route::get('getUsers', 'Datatables\UsersController@getUsers')->name('getUsers');
    Route::get('getTasks', 'Datatables\TasksController@getTasks')->name('getTasks');
    Route::get('getAchs', 'Datatables\AchController@getAchs')->name('getAchs');

});

//////////////////////////// Last Update /////////////////////////////
Route::group(['prefix' => 'user', 'as' => 'user.', 'namespace' => 'User', 'middleware' => ['auth', 'user']], function () {

    // Route::resource('department', 'SetDepartmentController');
    //Route::resource('user', 'SetUserController');
    Route::resource('task', 'UserTasksController');
   // Route::get('task','UserTasksController@index');
    Route::resource('profile', 'UserProfileController');
    Route::resource('achievement', 'UserAchievementsController');
    Route::post('image-upload', 'UserProfileController@imageUploadPost')->name('image.upload.post');

//////////////////////////// Last Update /////////////////////////////

//    Route::resource('task', 'SectionTaskController');
//    Route::resource('user', 'SectionUserController');
//    Route::resource('collection', 'SectionCollectionController');
//    Route::get('profile', 'DepartmentController@editProfile')->name('profile');
//    Route::put('profile', 'DepartmentController@updateProfile')->name('profile.update');
//    Route::put('password', 'DepartmentController@updatePassword')->name('profile.password');
});

Route::get('/home', 'Controller@index')->name('home');

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');


Route::get('/logout', function () {
    Auth::logout();
    return redirect('/login');
})->name('home.loguot');

app/Http/Controllers/Department/Datatables/AchController.php
<?php

namespace App\Http\Controllers\Department\Datatables;

use App\Achievement;
use App\Http\Controllers\Controller;
use App\Task;
use Illuminate\Http\Request;

class AchController extends Controller
{
    public function getAchs(Request $request)
    {
        $data = Achievement::with(['task.department.set', 'user'])
            ->get()->map(function ($item){
                $item->username = $item->user->name;
                $item->TaskName = $item->task->name;
                $item->TaskName = $item->task->name;
                $item->DepartmentName = $item->task->department->name;
                $item->SetName = $item->task->department->set->name;
                return $item;
            });

//        dd($data->first());
        return \DataTables::of($data)
            ->addColumn('Actions', function ($data) {
                $btn = '<a title="تعديل الانجاز "  href="' . route('department.ach.edit', $data->id) . '"  class="PopUp btn btn-outline-primary btn-sm m-btn m-btn--icon  m-btn--icon-only m-btn--pill"><i class="flaticon-settings"></i></a>
                <a  title="حذف الانجاز"  tname="AchTable" href="' . route('department.ach.destroy', $data->id) . '" class="Confirm  btn btn-outline-danger btn-sm m-btn m-btn--icon  m-btn--icon-only m-btn--pill"><i class="flaticon-delete-1"></i></a>';
                return $btn;
            })
            ->rawColumns(['Actions'])
            ->make(true);
    }
}

app/Http/Controllers/Department/Datatables/TasksController.php
<?php

namespace App\Http\Controllers\Department\Datatables;

use App\Http\Controllers\Controller;
use App\Task;
use Illuminate\Http\Request;

class TasksController extends Controller
{

    public function getTasks(Request $request)
    {
        $data = Task::with('department', 'achievement','user')
            ->where('department_id', self::getAuthDepartmentID())
            ->get()->map(function ($task){
                $task->username = $task->user->name;
                return $task;
            });

//        dd($data->first());
        return \DataTables::of($data)
            ->addColumn('Actions', function ($data) {
                $btn = '<a title="تعديل المهمة "  href="' . route('department.task.edit', $data->id) . '"  class="PopUp btn btn-outline-primary btn-sm m-btn m-btn--icon  m-btn--icon-only m-btn--pill"><i class="flaticon-settings"></i></a>
                <a  title="حذف المهمة"  tname="TaskTable" href="' . route('department.task.destroy', $data->id) . '" class="Confirm  btn btn-outline-danger btn-sm m-btn m-btn--icon  m-btn--icon-only m-btn--pill"><i class="flaticon-delete-1"></i></a>';
                return $btn;
            })
            ->rawColumns(['Actions'])
            ->make(true);
    }
}

app/Http/Controllers/Department/Datatables/UsersController.php
<?php

namespace App\Http\Controllers\Department\Datatables;

use App\Http\Controllers\Controller;
use App\User;
use Illuminate\Http\Request;

class UsersController extends Controller
{
    public function getUsers(Request $request)
    {

        $data = User::with('department', 'set', 'role')
            ->where('department_id', self::getAuthDepartmentID())
            ->get()->map(function ($item) {
                $item->DepName = $item->department->name;
                $item->SetName = $item->set->name;
                $item->RoleName = $item->role->name;
                return $item;
            });

//        dd($data->first());
        return \DataTables::of($data)
            ->addColumn('Actions', function ($data) {
                $btn = '<a title="تعديل المستخدم"  href="' . route('department.user.edit', $data->id) . '"  class="PopUp btn btn-outline-primary btn-sm m-btn m-btn--icon  m-btn--icon-only m-btn--pill"><i class="flaticon-settings"></i></a>
                <a  title="حذف المستخدم"  tname="UsersTable" href="' . route('department.user.destroy', $data->id) . '" class="Confirm  btn btn-outline-danger btn-sm m-btn m-btn--icon  m-btn--icon-only m-btn--pill"><i class="flaticon-delete-1"></i></a>';
                return $btn;
            })
            ->rawColumns(['Actions'])
            ->make(true);
    }
}

app/Http/Controllers/Department/DepartmentAchController.php
<?php

namespace App\Http\Controllers\Department;

use App\Achievement;
use App\Http\Controllers\Controller;
use App\Task;
use Illuminate\Database\QueryException;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Validator;

class DepartmentAchController extends Controller
{
    public function __construct()
    {

        $this->title_en = 'ach';
        $this->title_ar = 'الانجاز';
        $this->path = 'Department.Ach.';
    }

    public function index()
    {
        return view($this->path . 'index', [
            'Achs' => Achievement::all()
        ]);
    }//end of index

    public function create()
    {
        return view($this->path . 'create', [
            'tasks' => Task::where('department_id', '=', self::getAuthDepartmentID())->get()
        ]);
    }//end of create


    public function store(Request $request)
    {
        $validate = Validator::make($request->all(), $this->rules(), $this->messages());
        if ($request->task < 0) {
            $text = "e:اختر مهمة ";
            return response(['status' => false, 'close' => 0, 'msg' => $text, 'title' => $this->title_ar]);

        }
        if ($validate->fails()) {
            $text = "e:تاكد من البيانات";
//            dd($text);

            return response(['status' => false, 'errors' => $validate->messages(), 'msg' => $text], 422);
        } else {
            try {
                $ads = Achievement::create([
                    'name' => $request->name,
                    "description" => $request->description,
                    "task_id" => $request->task,
                    "user_id" => self::authId(),
                ]);

                $text = "s:تمت اضافة " . $this->title_ar . " بنجاح";
                return response(['status' => true, 'close' => 1, 'msg' => $text, 'title' => $this->title_ar]);
            } catch (QueryException $queryException) {
                $text = "e:لم يتم اضافة " . $this->title_ar . " بنجاح";
                return response(['status' => false, 'close' => 0, 'msg' => $text, 'title' => $this->title_ar]);
            }
        }
    }




    public function edit(Achievement $ach)
    {
        return view($this->path . 'edit', [
            'ach'=> $ach,
            'tasks' => Task::where('department_id', '=', self::getAuthDepartmentID())->get(),
        ]);
    }



    public function update(Request $request, Achievement $ach)
    {
        $validate = Validator::make($request->all(), $this->rules($ach->id), $this->messages($ach->id));

        if ($request->task < 0) {
            $text = "e:اختر مهمة ";
            return response(['status' => false, 'close' => 0, 'msg' => $text, 'title' => $this->title_ar]);

        }


        if ($validate->fails()) {
            $text = "e:تاكد من البيانات";
//            dd($text);

            return response(['status' => false, 'errors' => $validate->messages(), 'msg' => $text], 422);
        } else {
            try {

                $ach->update([
                    'name' => $request->name,
                    "description" => $request->description,
                    "task_id" => $request->task,
                ]);

                $text = "s:تمت اضافة " . $this->title_ar . " بنجاح";
                return response(['status' => true, 'close' => 1, 'msg' => $text, 'title' => $this->title_ar]);
            } catch (QueryException $queryException) {
                $text = "e:لم يتم اضافة " . $this->title_ar . " بنجاح";
                return response(['status' => false, 'close' => 0, 'msg' => $text, 'title' => $this->title_ar]);
            }
        }
    }


    public function destroy(Achievement $ach)
    {
        try {

            $ach->delete();
            $text = "s: تمت الحذف  " . $this->title_ar . " بنجاح";
            return response(['status' => true, 'close' => 1, 'msg' => $text, 'title' => $this->title_ar]);
        } catch (QueryException $queryException) {
            $text = "e:المهمة غير موجود";
            return response(['status' => false, 'close' => 0, 'msg' => $text, 'title' => $this->title_ar]);
        }
    }



    private function rules($id = null)
    {
        $rules = [
            'name' => 'required|min:3',
            'description' => 'required',
        ];

        return $rules;

    }

    private function messages($id = null)
    {
        return [
            'name.required' => 'الاسم مطلوب',
            'name.min' => 'الاسم يجب ان يحتوي ع الاقل 3 احرف',

        ];
    }


}

app/Http/Controllers/Department/DepartmentTaskController.php
<?php

namespace App\Http\Controllers\Department;

use App\Http\Controllers\Controller;
use App\Task;
use App\User;
use Illuminate\Database\QueryException;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Validator;

class DepartmentTaskController extends Controller
{
    public function __construct()
    {

        $this->title_en = 'task';
        $this->title_ar = 'المهمة ';
        $this->path = 'Department.Task.';
    }

    public function index()
    {
        return view($this->path . 'index');
    }

    public function create()
    {
        return view($this->path . 'create');
    }

    public function store(Request $request)
    {
        $validate = Validator::make($request->all(), $this->rules(), $this->messages());

        if ($validate->fails()) {
            $text = "e:تاكد من البيانات";
//            dd($text);

            return response(['status' => false, 'errors' => $validate->messages(), 'msg' => $text], 422);
        } else {
            try {
                $ads = Task::create([
                    'name' => $request->name,
                    "description" => $request->description,
                    "department_id" => self::getAuthDepartmentID(),
                    "user_id" => self::authId(),
                    'progress' =>null,
                    'IsDone' => false
                ]);

                $text = "s:تمت اضافة " . $this->title_ar . " بنجاح";
                return response(['status' => true, 'close' => 1, 'msg' => $text, 'title' => $this->title_ar]);
            } catch (QueryException $queryException) {
                $text = "e:لم يتم اضافة " . $this->title_ar . " بنجاح";
                return response(['status' => false, 'close' => 0, 'msg' => $text, 'title' => $this->title_ar]);
            }
        }
    }





    public function edit(Task $task)
    {
      return view($this->path . 'edit',[
          'task' => $task,
          'users'=>User::where('department_id','=',self::getAuthDepartmentID())->get()

      ]);
    }



    public function update(Request $request, Task $task)
    {
        $validate = Validator::make($request->all(), $this->rules($task->id), $this->messages($task->id));

        if ($validate->fails()) {
            $text = "e:تاكد من البيانات";
//            dd($text);

            return response(['status' => false, 'errors' => $validate->messages(), 'msg' => $text], 422);
        } else {
            try {

                $ads = $task->update([
                    'name' => $request->name,
                    "description" => $request->description,
                ]);

                $text = "s:تمت اضافة " . $this->title_ar . " بنجاح";
                return response(['status' => true, 'close' => 1, 'msg' => $text, 'title' => $this->title_ar]);
            } catch (QueryException $queryException) {
                $text = "e:لم يتم اضافة " . $this->title_ar . " بنجاح";
                return response(['status' => false, 'close' => 0, 'msg' => $text, 'title' => $this->title_ar]);
            }
        }
    }



    public function destroy(Task $task)
    {
        try {

            $task->delete();
            $text = "s: تمت الحذف  " . $this->title_ar . " بنجاح";
            return response(['status' => true, 'close' => 1, 'msg' => $text, 'title' => $this->title_ar]);
        } catch (QueryException $queryException) {
            $text = "e:المهمة غير موجود";
            return response(['status' => false, 'close' => 0, 'msg' => $text, 'title' => $this->title_ar]);
        }
    }

    private function rules($id = null)
    {
        $rules = [
            'name' => 'required|min:3',
            'description' => 'required',
        ];

        return $rules;

    }
    private function messages($id = null)
    {
        return [
            'name.required' => 'الاسم مطلوب',
            'name.min' => 'الاسم يجب ان يحتوي ع الاقل 3 احرف',

        ];
    }

}

resources/views/Department/Ach/create.blade.php
<form method="post" class="ajaxForm" tname="AchTable" action="{{route('department.ach.store')}}"
      enctype="multipart/form-data">
    @csrf
    <div class="row">
        <div class="col-md-6">
            <div class="form-group">
                <label class="control-label">اسم الإنجاز</label>
                <input type="text" name="name" class="form-control" required/>
                <span name="nname" class="text-danger error"></span>
            </div>
        </div>
        <div class="col-md-6">
            <div class="form-group">
                <label class="control-label">وصف الإنجاز</label>
                <input type="text" name="description" class="form-control" required/>
                <span name="edescription" class="text-danger error"></span>
            </div>
        </div>

    </div>


    <div class="row">
        <div class="col-md-6">
            <div class="form-group">
                <label for="task">اسم المهمة</label>
                <select name="task" id="task" class="form-control">
                    <option value="-1" selected>اختر مهمة</option>
                    @foreach($tasks as $task)

                    <option value="{{$task->id}}" >{{$task->name}}</option>
                    @endforeach
                </select>

            </div>
        </div>
    </div>





    <div class="form-group">
        <input type="submit" value="اضافة" class="btn btn-primary"/>
        <button type="button" class="btn btn-default waves-effect" data-dismiss="modal">الغاء الامر</button>
    </div>
</form>


<form asp-action="Create" method="post" class="ajaxForm" tname="AchTable">
    <div asp-validation-summary="ModelOnly" class="text-danger"></div>

</form>


<script>
    PageLoadActions();
</script>

resources/views/Department/Ach/edit.blade.php
<form method="post" class="ajaxForm" tname="AchTable" action="{{route('department.ach.update',$ach->id)}}"
      enctype="multipart/form-data">
    @csrf
    @method('PUT')
    <div class="row">
        <div class="col-md-6">
            <div class="form-group">
                <label class="control-label">اسم الإنجاز</label>
                <input type="text" name="name" class="form-control" required value="{{$ach->name}}"/>
                <span name="nname" class="text-danger error"></span>
            </div>
        </div>
        <div class="col-md-6">
            <div class="form-group">
                <label class="control-label">وصف الإنجاز</label>
                <input type="text" name="description" class="form-control" required value="{{$ach->description}}"/>
                <span name="edescription" class="text-danger error"></span>
            </div>
        </div>

    </div>


    <div class="row">
        <div class="col-md-6">
            <div class="form-group">
                <label for="task">اسم المهمة</label>
                <select name="task" id="task" class="form-control">
                    <option value="-1" selected>اختر مهمة</option>
                    @foreach($tasks as $task)

                    <option value="{{$task->id}}" {{($task->id === $ach->task_id)? 'selected' : ''}} >{{$task->name}}</option>
                    @endforeach
                </select>

            </div>
        </div>
    </div>





    <div class="form-group">
        <input type="submit" value="تعديل" class="btn btn-primary"/>
        <button type="button" class="btn btn-default waves-effect" data-dismiss="modal">الغاء الامر</button>
    </div>
</form>


<form asp-action="Create" method="post" class="ajaxForm" tname="AchTable">
    <div asp-validation-summary="ModelOnly" class="text-danger"></div>

</form>


<script>
    PageLoadActions();
</script>

resources/views/Department/Ach/index.blade.php
@extends('base_layout.master_layout')
@section('title','test')
@section('style')

    <style>
        td {
            padding: 4px 1px 0px 1px !important;
            font-size: 11px !important
        }

        td a {
            margin-left: 5px !important;
        }

        .m-portlet__body {
            padding-top: 0px !important;
        }
    </style>
@endsection
@section('content')


    <div class="m-portlet m-portlet--mobile">
        <div class="m-portlet__head">
            <div class="m-portlet__head-caption">
                <div class="m-portlet__head-title">
                    <h3 class="m-portlet__head-text">
                        <span style="color : lightslategray">فهرس المهام في الانجازات</span>
                        <small style="color : gray">عرض وتعديل بيانات الانجازات</small>
                    </h3>
                </div>
            </div>
            <div class="m-portlet__head-tools">
                <ul class="m-portlet__nav">
                    <li class="m-portlet__nav-item">
                        <a href="{{route('department.ach.create')}}" title="اضافة الانجازات  جديد "
                           class="PopUp btn-sm btn btn-outline-primary m-btn m-btn--custom m-btn--icon m-btn--pill m-btn--air">
                        <span>
                            <i class="fa fa-plus-square"></i>
                            <span>Add</span>
                        </span>
                        </a>
                    </li>
                    <li class="m-portlet__nav-item">
                        <a href="#" title="تصدير الى اكسل"
                           class="btn btn-sm btn-outline-success m-btn m-btn--custom m-btn--icon m-btn--pill m-btn--air">
                        <span>
                            <i class="fa fa-file-excel"></i>
                            <span>Excel</span>
                        </span>
                        </a>
                    </li>

                </ul>
            </div>
        </div>
        <div class="m-portlet__body">

            <!--begin: Search Form -->
            <div class="m-form m-form--label-align-right m--margin-top-10 m--margin-bottom-0">
                <div class="row align-items-center">
                    <div class="col-xl-8 order-2 order-xl-1">
                        <div class="form-group m-form__group row align-items-center">
                            <div class="col-md-6">
                                <div class="m-input-icon m-input-icon--left">
                                    <input type="text" name="SearchKey" class="form-control m-input m-input--air"
                                           placeholder="اسم الانجاز.. ">
                                </div>
                            </div>
                            <div class="col-md-2">
                                <a class="SearchBtn btn btn-outline-brand m-btn m-btn--icon btn-sm m-btn--icon-only m-btn--custom m-btn--outline-1x m-btn--pill m-btn--air">
                                    <i class="fa fa-search"></i>
                                </a>
                            </div>

                        </div>
                    </div>

                </div>
            </div>
            <table class="table m-table m-table--head-separator-primary" id="AchTable">

                <!-- <table class="table table-bordered data-table"> -->
                <thead>
                <tr>
                    <th>كاتب الانجاز</th>
                    <th>عنوان الانجاز</th>
                    <th>وصف الانجاز</th>
                    <th>المهمة</th>
                    <th>نسبة الانجاز</th>
                    <th>الدائرة</th>
                    <th>القسم</th>
                    <th>تاريخ</th>
                    <th width="100px">العمليات</th>
                </tr>
                </thead>
                <tbody>
                </tbody>
            </table>

        </div>

    </div>


@endsection
@section('script')


    <script type="text/javascript">
        $(function () {

            var table = $('#AchTable').DataTable({
                language: {
                    aria: {
                        sortAscending: ": فعال لترتيب العمود تصاعديا",
                        sortDescending: ": فعال لترتيب العمود تنازليا"
                    },
                    emptyTable: "لا يوجد بيانات لعرضها",
                    info: "عرض _START_ الى _END_ من _TOTAL_ صف",
                    infoEmpty: "لا يوجد نتائج لعرضها",
                    infoFiltered: "(filtered1 من _MAX_ اجمالي صفوف)",
                    lengthMenu: "_MENU_",
                    search: "بحث",
                    zeroRecords: "لا يوجد نتائج لعرضها",
                    paginate: {
                        sFirst: "الاول",
                        sLast: "الاخير",
                        sNext: "التالي",
                        sPrevious: "السابق"
                    }
                },
                "bLengthChange": false,
                "deferRender": true,
                processing: true,
                serverSide: true,
                "searching": false,

                ajax: "{{ route('department.getAchs') }}",

                columns: [
                    {
                        data: 'username',
                        name: 'username'
                    },
                    {
                    data: 'name',
                    name: 'name'
                },
                    {
                        data: 'description',
                        name: 'description'
                    },

                    {
                        data: 'TaskName',
                        name: 'TaskName'
                    },
                    {
                        data: 'TaskName',
                        name: 'TaskName'
                    },

                    {
                        data: 'DepartmentName',
                        name: 'DepartmentName'
                    },

                    {
                        data: 'SetName',
                        name: 'SetName'
                    },


                     {
                        data: 'created_at',
                        name: 'created_at'
                    },
                    {
                        data: 'Actions',
                        name: 'Actions',
                        orderable: false,
                        searchable: false
                    },
                ],

            });

        });

    </script>



@endsection