routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Route::get('cache', function () {
    Artisan::call('cache:clear');
    Artisan::call('config:clear');
    Artisan::call('view:clear');

    dd('success');
});

Route::redirect('/', 'login');

Auth::routes();

Route::get('test', 'testController@index');


Route::group(['prefix' => 'admin', 'as' => 'admin.', 'namespace' => 'Admin', 'middleware' => ['auth', 'admin']], function () {
    Route::resource('messages', 'AdminMessageController');
    Route::resource('department', 'AdminDepartmentController');
    Route::resource('user', 'AdminUserController');
    Route::resource('task', 'AdminTaskController');
    Route::resource('set', 'AdminSetController');
    Route::resource('role', 'AdminRoleController');
    Route::resource('achievement', 'AdminAchievementsController');
    Route::resource('profile', 'AdminProfileController');
    Route::post('image-upload', 'AdminProfileController@imageUploadPost')->name('image.upload.post');

    //Route::get('profile', 'AdminController@editProfile')->name('profile');
    // Route::get('profile', 'AdminController@editProfile')->name('profile');
    Route::put('profile', 'AdminController@updateProfile')->name('profile.update');
    Route::put('password', 'AdminController@updatePassword')->name('profile.password');

});


//////////////////////////// Last Update /////////////////////////////
Route::group(['prefix' => 'set', 'as' => 'set.', 'namespace' => 'Set', 'middleware' => ['auth', 'sets']], function () {

    Route::resource('department', 'SetDepartmentController');
    Route::resource('user', 'SetUserController');
    Route::resource('profile', 'SetProfileController');
    Route::post('image-upload', 'SetProfileController@imageUploadPost')->name('image.upload.post');

//////////////////////////// Last Update /////////////////////////////

//    Route::resource('task', 'SectionTaskController');
//    Route::resource('user', 'SectionUserController');
//    Route::resource('collection', 'SectionCollectionController');
//    Route::get('profile', 'DepartmentController@editProfile')->name('profile');
//    Route::put('profile', 'DepartmentController@updateProfile')->name('profile.update');
//    Route::put('password', 'DepartmentController@updatePassword')->name('profile.password');
});


Route::group(['prefix' => 'department', 'as' => 'department.', 'namespace' => 'Department', 'middleware' => ['auth', 'department']], function () {
//    Route::resource('collection', 'DepartmentCollectionController');
//    Route::resource('section', 'DepartmentSectionController');
    Route::get('home', function () {
        return view('Department.home');
    })->name('home');
    Route::resource('user', 'DepartmentUserController');
    Route::resource('task', 'DepartmentTaskController');
    Route::resource('ach', 'DepartmentAchController');
    Route::get('profile', 'ProfileController@index')->name('profile');
//    Route::put('profile', 'DepartmentController@updateProfile')->name('profile.update');
//    Route::put('password', 'DepartmentController@updatePassword')->name('profile.password');
    //Datatables
    Route::get('getUsers', 'Datatables\UsersController@getUsers')->name('getUsers');
    Route::get('getTasks', 'Datatables\TasksController@getTasks')->name('getTasks');
    Route::get('getAchs', 'Datatables\AchController@getAchs')->name('getAchs');

});

//////////////////////////// Last Update /////////////////////////////
Route::group(['prefix' => 'user', 'as' => 'user.', 'namespace' => 'User', 'middleware' => ['auth', 'user']], function () {

    // Route::resource('department', 'SetDepartmentController');
    //Route::resource('user', 'SetUserController');
    Route::resource('task', 'UserTasksController');
   // Route::get('task','UserTasksController@index');
    Route::resource('profile', 'UserProfileController');
    Route::resource('achievement', 'UserAchievementsController');
    Route::post('image-upload', 'UserProfileController@imageUploadPost')->name('image.upload.post');

//////////////////////////// Last Update /////////////////////////////

//    Route::resource('task', 'SectionTaskController');
//    Route::resource('user', 'SectionUserController');
//    Route::resource('collection', 'SectionCollectionController');
//    Route::get('profile', 'DepartmentController@editProfile')->name('profile');
//    Route::put('profile', 'DepartmentController@updateProfile')->name('profile.update');
//    Route::put('password', 'DepartmentController@updatePassword')->name('profile.password');
});

Route::get('/home', 'Controller@index')->name('home');

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');


Route::get('/logout', function () {
    Auth::logout();
    return redirect('/login');
})->name('home.loguot');

app/User.php
<?php

namespace App;

use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;

class User extends Authenticatable
{
    use Notifiable;

   protected $table = 'users';
    protected $fillable = [
        'name', 'email', 'password', 'department_id', 'set_id', 'role_id','password_confirmation'
    ];

    protected $hidden = [
        'password', 'remember_token',
    ];


    protected $casts = [
        'email_verified_at' => 'datetime',
    ];

    public function hasRole($role)
    {
        $roleName = Role::find($role)->select('name');
        return $this->role == $roleName;
    }

    public function tasks()
    {
        return $this->hasMany(Task::class, 'user_id');
    }

    public function department()
    {
        return $this->belongsTo(Department::class);
    }

    public function set()
    {
        return $this->belongsTo(Set::class);
    }

    public function role()
    {
        return $this->belongsTo(Role::class);
    }

    public function information()
    {
        return $this->hasOne(UserInformation::class);
    }

    public function communication()
    {
        return $this->hasMany(UserCommunication::class);
    }

    public function medias()
    {
        return $this->hasMany(Media::class);
    }
   public function messages()
    {
        return $this->hasMany(Massage::class);
    }


//

}

app/Http/Controllers/Department/Datatables/UsersController.php
<?php

namespace App\Http\Controllers\Department\Datatables;

use App\Http\Controllers\Controller;
use App\User;
use Illuminate\Http\Request;

class UsersController extends Controller
{
    public function getUsers(Request $request)
    {

        $data = User::with('department', 'set', 'role')
            ->where('department_id', self::getAuthDepartmentID())
            ->get()->map(function ($item) {
                $item->DepName = $item->department->name;
                $item->SetName = $item->set->name;
                $item->RoleName = $item->role->name;
                return $item;
            });

//        dd($data->first());
        return \DataTables::of($data)
            ->addColumn('Actions', function ($data) {
                $btn = '<a title="تعديل المستخدم"  href="' . route('department.user.edit', $data->id) . '"  class="PopUp btn btn-outline-primary btn-sm m-btn m-btn--icon  m-btn--icon-only m-btn--pill"><i class="flaticon-settings"></i></a>
                <a  title="حذف المستخدم"  tname="UsersTable" href="' . route('department.user.destroy', $data->id) . '" class="Confirm  btn btn-outline-danger btn-sm m-btn m-btn--icon  m-btn--icon-only m-btn--pill"><i class="flaticon-delete-1"></i></a>';
                return $btn;
            })
            ->rawColumns(['Actions'])
            ->make(true);
    }
}

app/Http/Controllers/User/UserAchievementsController.php
<?php

namespace App\Http\Controllers\User;

use App\Achievement;
use App\Http\Controllers\Controller;
use App\Task;
use Illuminate\Http\Request;

class UserAchievementsController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function index()
    {
        $data['data'] = Achievement::with(['task', 'user'])->where('user_id', self::authId())->get();
        return view('user.achievement.index', $data);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function create()
    {
        $data['tasks'] = Task::where('department_id', self::getAuthDepartmentID())->pluck('name', 'id');
        return view('user.achievement.create', $data);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request $request
     * @return \Illuminate\Http\RedirectResponse
     */
    public function store(Request $request)
    {
        try {
            Achievement::create([
                'name' => $request->input('name'),
                'description' => $request->input('description'),
                'user_id' => self::authId(),
                'task_id' => $request->input('task_id'),
            ]);
            return redirect()->route('user.achievement.index')
                ->with('success', 'تمت عملية الإضافة بنجاح');
        } catch (\Exception $exception) {
            dd($request);
            return back()->with('danger', 'عذراً: حدث خلل أثناء الإرسال، حاول في وقت آخر' . $exception->getMessage());
        }
    }

    /**
     * Display the specified resource.
     *
     * @param  int $id
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function show($id)
    {

    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int $id
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function edit($id)
    {
        try {
            $depId = Achievement::findOrFail($id);
            return view('user.achievement.edit')->with('depId', $depId);
        } catch (\Exception $exception) {
            abort(404);
        }
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request $request
     * @param  int $id
     * @return \Illuminate\Http\RedirectResponse
     */
    public function update(Request $request, $id)
    {

        try {
            $updateDep = Achievement::findOrFail($id);
            $updateDep->name = $request->input('name');
            $updateDep->description = $request->input('description');

            $updateDep->update();
            return redirect()->route('user.achievement.index')
                ->with('success', "Department $updateDep->name OR $updateDep->description updated Successfully");
        } catch (\Exception $exception) {
            return redirect()->route('user.achievement.edit', [$id])->with('error', 'Update Fail');
        }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int $id
     * @return \Illuminate\Http\RedirectResponse
     */
    public function destroy($id)
    {
//        dd(1);
        try {
            $deleteID = Achievement::findOrFail($id);
            $deleteID->delete();
            return redirect()->route('user.achievement.index')->with('success', "تم حذف القسم بنجاح");
        } catch (\Exception $exception) {
//            dd(1);
            return redirect()->route('$deleteID')->with('error', 'عذرا !! هناك خطأ في عملية الحذف' . $exception);
        }

    }

}

app/Http/Controllers/User/UserController.php
<?php

namespace App\Http\Controllers\User;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;

class UserController extends Controller
{
    //
}

app/Http/Controllers/User/UserProfileController.php
<?php

namespace App\Http\Controllers\User;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;

class UserProfileController extends Controller
{
    //
}

app/Http/Controllers/User/UserTasksController.php
<?php

namespace App\Http\Controllers\User;

use App\Http\Controllers\Controller;
use App\Task;
use Illuminate\Http\Request;

class UserTasksController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function index()
    {
        $data['data'] = Task::with(['user'])->where('department_id', self::getAuthDepartmentID())->get();
        return view('user.task.index', $data);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function create()
    {
        $data['tasks'] = Task::where('department_id', self::getAuthDepartmentID())->pluck('name', 'id');
        return view('user.task.create', $data);
    }

}

resources/views/admin/user/create.blade.php
@extends("layouts.public")

@section("title")
    إضافة مستخدم جديد
@endsection()

@section("css")

@endsection()

@section("content")
    <div class="content">

        @if (count($errors) > 0)
            <div class="alert alert-danger">
                <strong>Whoops!</strong> There were some problems with your input.<br><br>
                <ul>
                    @foreach ($errors->all() as $error)
                        <li>{{ $error }}</li>
                    @endforeach
                </ul>
            </div>
        @endif

        <div role="dialog">
            <div class="modal-dialog" style="width: 80% ;font-size: larger">
                <div class="modal-content">
                    <div class="modal-header">
                        <div class="row">
                            <div class="col-lg-12 margin-tb">
                                <div class="pull-left">
                                    <h1 class="text-center" style="font-family: 'Al-Jazeera'">
                                        {{"إضافة مستخدم جديد"}}
                                    </h1>
                                </div>
                                <div class="pull-right">
                                    <a class="btn btn-primary" href="{{ route('admin.user.index') }}"> رجوع</a>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="modal-body">
                        {!!Form::open(array('route' => 'admin.user.store','method'=>'POST','class'=>'form-horizontal','role'=>'form')) !!}
                        <div class="form-group">
                            <label class="control-label col-sm-3" for="title">اسم المستخدم</label>
                            <div class="col-sm-9">
                                {!! Form::text('name', null, array('placeholder' => 'اسم المستخدم','class' => 'form-control')) !!}
                            </div>
                        </div>

                        <div class="form-group">
                            <label class="control-label col-sm-3" for="title">البريد الإلكتروني</label>
                            <div class="col-sm-9">
                                {!! Form::text('email', null, array('placeholder' => 'البريد الإلكتروني','class' => 'form-control')) !!}
                            </div>
                        </div>

                        <div class="form-group">
                            <label class="control-label col-sm-3" for="title">كلمة المرور</label>
                            <div class="col-sm-9">
                                {!! Form::password('password', array('placeholder' => 'كلمة المرور','class' => 'form-control')) !!}
                            </div>
                        </div>

                        <div class="form-group">
                            <label class="control-label col-sm-3" for="title">تأكيد كلمة المرور</label>
                            <div class="col-sm-9">
                                {!! Form::password('password_confirmation', array('placeholder' => 'تأكيد كلمة المرور','class' => 'form-control')) !!}
                            </div>
                        </div>

                        <div class="form-group">
                            <label for="fullname" class="col-sm-3 control-label">الدائرة </label>
                            <div class="col-sm-9">
                                <select class="form-control" name="set_id" required>
                                    <option value="">-- اختر الدائرة --</option>
                                    @foreach($set as $item)
                                        <option value="{{$item->id}}"> {{$item->name}}</option>
                                    @endforeach

                                </select>
                            </div>
                        </div>

                        <div class="form-group">
                            <label for="fullname" class="col-sm-3 control-label">القسم </label>
                            <div class="col-sm-9">
                                <select class="form-control" name="department_id" required>
                                    <option value="">-- اختر القسم --</option>
                                    @foreach($department as $item)
                                        <option value="{{$item->id}}"> {{$item->name}}</option>
                                    @endforeach

                                </select>
                            </div>
                        </div>
                        <div class="form-group">
                            <label for="fullname" class="col-sm-3 control-label">الصلاحية </label>
                            <div class="col-sm-9">
                                {!!Form::select('role_id',$role, null, ['placeholder' => '-- إختر الصلاحية --','class'=>'form-control'])!!}
                            </div>
                        </div>
                        <div class="modal-footer">
                            <button type="submit" class="btn btn-success add">
                                <span class='glyphicon glyphicon-check'></span>حفظ
                            </button>
                            {{-- <button type="button" class="btn btn-warning" data-dismiss="modal">
                                 <span class='glyphicon glyphicon-remove'></span> إغلاق
                             </button>--}}
                            <a class="btn btn-primary" href="{{ route('admin.user.index') }}"> <span
                                        class='glyphicon glyphicon-remove'></span> رجوع</a>
                        </div>
                        {!! Form::close() !!}
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection()

resources/views/admin/user/edit.blade.php
@extends("layouts.public")

@section("title")
    تعديل بيانات المستخدم
@endsection()

@section("css")

@endsection()

@section("content")
    <div class="content">

        @if (count($errors) > 0)
            <div class="alert alert-danger">
                <strong>Whoops!</strong> There were some problems with your input.<br><br>
                <ul>
                    @foreach ($errors->all() as $error)
                        <li>{{ $error }}</li>
                    @endforeach
                </ul>
            </div>
        @endif

        <div role="dialog">
            <div class="modal-dialog" style="width: 80% ;font-size: larger">
                <div class="modal-content">
                    <div class="modal-header">
                        <div class="row">
                            <div class="col-lg-12 margin-tb">
                                <div class="pull-left">
                                    <h1 class="text-center" style="font-family: 'Al-Jazeera'">
                                        {{"تعديل بيانات المستخدم"}}
                                    </h1>
                                </div>
                                <div class="pull-right">
                                    <a class="btn btn-primary" href="{{ route('admin.user.index') }}"> رجوع</a>
                                </div>
                            </div>
                        </div>
                    </div>

                    <div class="modal-body">
                        {!!Form::open(array('route' => ['admin.user.update',$updateUser->id],'method'=>'POST','class'=>'form-horizontal','role'=>'form')) !!}
                        @method('PUT')

                        <div class="form-group">
                            <label class="control-label col-sm-3" for="title">اسم المستخدم</label>
                            <div class="col-sm-9">
                                {!! Form::text('name', $updateUser->name, array('placeholder' => 'اسم المستخدم','class' => 'form-control')) !!}
                            </div>
                        </div>

                        <div class="form-group">
                            <label class="control-label col-sm-3" for="title">البريد الإلكتروني</label>
                            <div class="col-sm-9">
                                {!! Form::text('email', $updateUser->email, array('placeholder' => 'البريد الإلكتروني','class' => 'form-control')) !!}
                            </div>
                        </div>

                        <div class="form-group">
                            <label class="control-label col-sm-3" for="title">كلمة المرور</label>
                            <div class="col-sm-9">
                                {!! Form::password('password', array('placeholder' => 'كلمة المرور','class' => 'form-control')) !!}
                            </div>
                        </div>

                        <div class="form-group">
                            <label class="control-label col-sm-3" for="title">تأكيد كلمة المرور</label>
                            <div class="col-sm-9">
                                {!! Form::password('password_confirmation', array('placeholder' => 'تأكيد كلمة المرور','class' => 'form-control')) !!}
                            </div>
                        </div>

                        <div class="form-group">
                            <label for="fullname" class="col-sm-3 control-label">الدائرة </label>
                            <div class="col-sm-9">
                                <select class="form-control" name="set_id" required>
                                    <option value="">-- اختر الدائرة --</option>
                                    @foreach($set as $item)
                                        <option value="{{$item->id}}" {{ ( $item->id == $updateUser->set_id) ? 'selected' : '' }}> {{$item->name}}</option>
                                    @endforeach

                                </select>
                            </div>
                        </div>

                        <div class="form-group">
                            <label for="fullname" class="col-sm-3 control-label">القسم </label>
                            <div class="col-sm-9">
                                <select class="form-control" name="department_id" required>
                                    <option value="">-- اختر القسم --</option>
                                    @foreach($department as $item)
                                        <option value="{{$item->id}}" {{ ( $item->id == $updateUser->department_id) ? 'selected' : '' }}> {{$item->name}}</option>
                                    @endforeach

                                </select>
                            </div>
                        </div>
                        <div class="form-group">
                            <label for="fullname" class="col-sm-3 control-label">الصلاحية </label>
                            <div class="col-sm-9">
                                {!!Form::select('role_id',$role, $updateUser->role_id, ['placeholder' => '-- إختر الصلاحية --','class'=>'form-control'])!!}
                            </div>
                        </div>
                        <div class="modal-footer">
                            <button type="submit" class="btn btn-success add">
                                <span class='glyphicon glyphicon-check'></span>حفظ
                            </button>
                            {{-- <button type="button" class="btn btn-warning" data-dismiss="modal">
                                 <span class='glyphicon glyphicon-remove'></span> إغلاق
                             </button>--}}
                            <a class="btn btn-primary" href="{{ route('admin.user.index') }}"> <span
                                    class='glyphicon glyphicon-remove'></span> رجوع</a>
                        </div>
                        {!! Form::close() !!}
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection()

resources/views/admin/user/index.blade.php
    @extends("layouts.public")

@section("title")
    المستخدمين
@endsection()

@section("css")

@endsection()

@section("content")

    <div class="content">
        <div class="tab-content">
            <div class="panel panel-white">
                <div class="panel-heading">
                    <h1 class="text-center" style="font-family: 'Al-Jazeera'">
                        {{"إدارة المستخدمين"}}
                    </h1>
                    <div class="heading-elements">
                        <a class="btn btn-success" href="{{ route('admin.user.create') }}">{{" إضافة مستخدم جديد"}}</a>
                    </div>
                </div>

                @if ($message = Session::get('success'))
                    <div class="alert alert-success">
                        <p>{{ $message }}</p>
                    </div>
                @endif
                <div class="row" style="font-size: initial">
                    <div class="col-md-12">
                        <table class="table datatable-basic">
                            <thead>
                            <tr>
                                <th>#</th>
                                <th>الاسم</th>
                                <th>الايميل</th>
                                <th>الدائرة</th>
                                <th>القسم</th>
                                <th>الصلاحية</th>
                                <th>تاريخ</th>
                                <th>الحدث</th>
                            </tr>
                            </thead>
                            @foreach ($data as $key => $item)

                            <tr>
                                    <td>{{$item->id }}</td>
                                    <td>{{$item->name}}</td>
                                    <td>{{ $item->email }}</td>
                                    <td>{{ $item->set->name ?? 'not Found' }}</td>
                                    <td>{{ $item->department->name ?? 'not Found'}}</td>
                                    <td>{{ $item->role->name ?? 'not Found'}}</td>
                                    <td>{{ date('d-m-Y', strtotime($item->created_at)) }} </td>
                                    <td style="width: 22%">
                                        <a class="edit-modal btn btn-info"
                                           href="{{ route('admin.user.edit',$item->id) }}">
                                            <i class="glyphicon glyphicon-edit"></i> تعديل
                                        </a>
                                        {!! Form::open(['method' => 'DELETE','route' => ['admin.user.destroy', $item->id],'style'=>'display:inline']) !!}
                                        {!! Form::button('<i class="glyphicon glyphicon-trash"></i> حذف', ['type' => 'submit','class' => 'btn btn-danger']) !!}
                                        {!! Form::close() !!}
                                    </td>
                                </tr>
                            @endforeach
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div class="content">
        <div class="col-lg-10">
            <form method="get" action="{{--{{url('admin/category')}}--}}" class="row">
                <div class="col-sm-3">
                    <input autofocus name="q" type="text" value="{{--{{$q}}--}}" class="form-control"
                           placeholder="بحث عن مستخدم...">
                </div>

                <div class="col-sm-2">
                    <select class="form-control" name="is_active">
                        <option value=""> جميع الأقسام</option>
                        <option value="1"> ويب</option>
                        <option value="0"> اندرويد</option>
                    </select>
                </div>


                <span class="col-sm-1">
                    <button class="btn btn-primary" type="submit">بحث!</button>
                  </span>
            </form><!-- /input-group -->
        </div>
        <div class="col-lg-2 text-right"><a class="btn btn-success" href="{{route('admin.user.create')}}"> إضافة مستخدم
                جديد</a></div>
    </div>

@endsection()

@section("js")
    <!-- Theme JS files -->
    <script src="{{asset('global_assets/js/plugins/tables/datatables/datatables.min.js') }}"></script>
    <script src="{{asset('global_assets/js/plugins/forms/selects/select2.min.js') }}"></script>

    <script src="{{asset('global_assets/js/demo_pages/datatables_basic.js') }}"></script>
    <!-- /theme JS files -->
@endsection()